### ISSUE TITLE
MLSD not implemented

### ISSUE THREAD

**Issue by urielarg** [pohmelie/aioftp#39]
I tried your example with my a common FTP server app on the phone, I kept getting 502 for MLSD command. I'm very newbie in all this but doing some research I found MLSD is new and commonly falls back to LIST, I've tested it and it does work. Will it be possible to have it as a fallback? I'm happy to fork and make a pull request if you think it makes sense.

**Comment by pohmelie** [comment]
@urielarg 
`MLSD` is not «new», it's from 2007 [rfc3659](https://tools.ietf.org/html/rfc3659). Since `LIST` have no standard, parsing is «dangerous» :smile: 
Just look at [FileZilla's parsing](https://svn.filezilla-project.org/filezilla/FileZilla3/trunk/src/engine/directorylistingparser.cpp?revision=7322&view=markup) code. If you want, you can try to make it proper working with fallback. But I think in this case you can just inherrit `aioftp.Server` class and reimplement `list` for parsing your FTP server response only. Cause implementing whole cases would be painful and borring.

**Comment by heftig** [comment]
From my cursory tests neither `bftpd` nor `vsftpd` seem to implement `MSLD` or `MSLT`. Please consider reopening this and implementing fallbacks for either command.

**Comment by pohmelie** [comment]
@heftig 
As I said before, feel free to implement full `LIST` parsing, and we will make fall-back. But I think, that `LIST` is for humans, `MLSx` is for machines. I'm really disappointed why server-creators still did not release this functionality. It's not new, it's not too hard. So it is better to create issue for `bftpd` and `vsftpd` and ask them «why so?».
