### ISSUE TITLE
Client/ClientSession Download

### ISSUE THREAD

**Issue by pmart123** [pohmelie/aioftp#40]
I first want to thank you for putting this library together. I tried to use the higher level download, but I received this error.

``` python
aioftp.errors.StatusCodeError: Waiting for ('2xx',) but got 500 [" 'MLST my_path: command not understood."]
```

The ftp sever I'm trying to connect to doesn't support MLST, and download uses an is_file method, which uses MLST. Would you be open to changing the code so download just assumes the developer knows what they are doing/is inputting a correct file source path? This would eliminate the error/reliance on MLST for downloading a file.

**Comment by pohmelie** [comment]
I think `download_file` and `upload_file` should be implemented in client. This cover your case and will have no extra code. I will do it in couple days, since now I'm busy a little.

**Comment by pohmelie** [comment]
After some time of rethinking of it, I think that `download_file` does not fit the `aioftp` way. Since this is «mid-level» api which the only purpose is to avoid `MLST`, which is standard since 2007. And we can't just assume the developer knows what they are doing, since `download` is recursive and can download whole directories it must do file/dir check.
My suggestion here will be to subclass `aioftp.Client` and redefine `is_file` coroutine like this:
``` python
class MyClient(aioftp.Client):

    async def is_file(self, path):

        return True
```
This will remove `MLST` request in `download` and you will get what you want. This does not fix `ClientSession` though.

**Comment by pohmelie** [comment]
@pmart123, I think since today this is resolved. Cause `aioftp` now support fallback to `LIST` command if `MLSx` will be not implemented on server side. Can you check it out?
