### ISSUE TITLE
"Waiting for ('200',) but got 250" when downloading a file

### ISSUE THREAD

**Issue by sametmax** [pohmelie/aioftp#45]
I start the aioftp server from the command line:

     python -m aioftp --user user --pass password

I can connect fine using filezilla and get "/fixture.csv" file.

When I do:

    async with aioftp.ClientSession(host, port, login, pwd) as client:
         while True:
             stream = await client.download_stream(path)
             print(await steam.read())
             await asyncio.sleep(1)

I can read the file the first time, then any next loop turn I get  a 'aioftp.errors.StatusCodeError' exception stating:

     aioftp.errors.StatusCodeError: Waiting for ('200',) but got 250 ['-start', ' Type=file;Size=2914;Modify=1471460964.99208;Create=1488359466.8050766; fixture.csv', ' end']% 

I get the same error if I fail to read the file. The completely break my crawler since the csv refresh every second. And I can't find any workaround.

**Comment by pohmelie** [comment]
First of all, `read` call reads maximum `DEFAULT_BLOCK_SIZE` bytes (right now it is 8192). If you want download whole file you need pass `-1` in `stream.read`, since it pushed down to `StreamReader` (https://docs.python.org/3/library/asyncio-stream.html?highlight=streamreader#asyncio.StreamReader.read).
Second part is that you should finish data connection with `await stream.finish()` or just use asynchronous context as documentation said (http://aioftp.readthedocs.io/client_tutorial.html#advanced-download-and-upload-abort-restart)

**Comment by sametmax** [comment]
Great thank you.
